# Generated by Django 4.0.4 on 2022-05-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('owner', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shopping_list',
                'ordering': ['-id'],
            },
        ),
    ]
